services:
  anon-bot:
    build: ../anon-bot/
    ports:
      - "8080:8080"
  anon-bot-messager:
    build: ../anon-bot-messager/
    ports:
      - "8000:8000"
    environment:
      - DISCORD_URL=${DISCORD_URL}