services:
  anon-bot:
    build: https://github.com/synth-evol/anon-bot.git
  anon-bot-messager:
    build: https://github.com/synth-evol/anon-bot-messager.git
    environment:
      - DISCORD_URL=${DISCORD_URL}
  caddy:
    image: caddy:2.7-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
